-- CivicFix AI: Supabase table for saved reports.
-- Run this once in Supabase Dashboard -> SQL Editor -> New query -> Run.

create extension if not exists pgcrypto;

create table if not exists public.reports (
  id                    uuid primary key default gen_random_uuid(),
  -- Generated by the browser once per analysis; the UNIQUE constraint makes a
  -- double click / retry save the same report only once.
  client_request_id     uuid not null unique,

  issue_category        text not null,
  issue_type            text not null,
  description           text not null default '',
  severity              text not null
                        check (severity in ('Low','Medium','High','Critical','Uncertain')),
  confidence            double precision not null check (confidence >= 0 and confidence <= 1),
  recommended_actions   jsonb not null default '[]'::jsonb,
  suggested_department  text,

  estimated_cost_min    numeric check (estimated_cost_min is null or estimated_cost_min >= 0),
  estimated_cost_max    numeric check (estimated_cost_max is null or estimated_cost_max >= 0),
  estimated_cost_basis  text,
  estimated_duration_min_hours numeric check (estimated_duration_min_hours is null or estimated_duration_min_hours >= 0),
  estimated_duration_max_hours numeric check (estimated_duration_max_hours is null or estimated_duration_max_hours >= 0),
  estimated_duration_basis     text,

  location              text not null default '',
  latitude              double precision check (latitude  is null or (latitude  between -90  and 90)),
  longitude             double precision check (longitude is null or (longitude between -180 and 180)),
  -- Coordinates are optional, but never half-filled.
  constraint reports_coordinates_pair check ((latitude is null) = (longitude is null)),

  status                text not null default 'Open'
                        check (status in ('Open','In Review','In Progress','Resolved','Closed')),
  created_at            timestamptz not null default now()
);

create index if not exists reports_created_at_idx on public.reports (created_at desc);
create index if not exists reports_status_idx     on public.reports (status);
create index if not exists reports_severity_idx   on public.reports (severity);

-- Lock the table down. The FastAPI backend uses the service/secret key, which
-- bypasses RLS. With RLS on and no policies, the public anon key can read or
-- write nothing, so nobody can reach the data straight from a browser.
alter table public.reports enable row level security;
