/**
 * CivicFix AI — reports data access
 * ==========================================================================
 * Analysis and storage are separate capabilities. POST /analyze produces an
 * assessment; it does NOT create a stored report unless the backend says so.
 *
 * This module is the only place the dashboard reads report data from, so the
 * presentation layer never has to change when real endpoints arrive.
 *
 * Current state of the backend contract: report retrieval is NOT implemented.
 * `fetchReports()` performs a real request and surfaces the real failure; the
 * dashboard then shows an honest empty state. `getDemoReports()` returns
 * clearly labelled sample data for interface preview only.
 */

import { getCategoryLabel } from '@/config/issueCategories'
import { API_BASE_URL, API_ERROR_CODES, ApiError, apiRequest } from '@/services/civicfixApi'

export const REPORTS_ENDPOINT = '/reports'

/**
 * Data source currently backing the dashboard.
 * @readonly
 */
export const REPORTS_DATA_SOURCE = {
  NONE: 'none',
  API: 'api',
  DEMO: 'demo',
}

/**
 * Set to `true` only once the backend actually stores and returns reports.
 * The UI copy is derived from this flag.
 */
export const REPORTS_STORAGE_AVAILABLE = false

export const REPORTS_NOT_AVAILABLE_MESSAGE =
  'Stored reports are not available yet. The agreed backend contract currently exposes only POST /analyze, ' +
  'which returns an assessment without saving it. Once a reports endpoint exists, this dashboard connects to it without interface changes.'

/**
 * Attempt to retrieve stored reports.
 *
 * Performs a real `GET {VITE_API_URL}/reports`. It is expected to fail today;
 * the thrown `ApiError` describes the real outcome. Nothing is substituted.
 *
 * @param {{ signal?: AbortSignal, timeoutMs?: number }} [options]
 * @returns {Promise<{ reports: Array<object>, source: string }>}
 */
export async function fetchReports({ signal, timeoutMs = 8000 } = {}) {
  try {
    const { data } = await apiRequest(REPORTS_ENDPOINT, { method: 'GET', signal, timeoutMs })

    const list = Array.isArray(data) ? data : Array.isArray(data?.reports) ? data.reports : null
    if (!list) {
      throw new ApiError(
        'The reports endpoint responded with a body that is not a list of reports. Expected an array or an object with a "reports" array.',
        { code: API_ERROR_CODES.UNEXPECTED_SCHEMA, url: `${API_BASE_URL}${REPORTS_ENDPOINT}` },
      )
    }

    return { reports: list.map((entry) => ({ ...entry, isDemo: false })), source: REPORTS_DATA_SOURCE.API }
  } catch (error) {
    if (error instanceof ApiError && error.status === 404) {
      throw new ApiError(REPORTS_NOT_AVAILABLE_MESSAGE, {
        code: API_ERROR_CODES.HTTP,
        status: 404,
        url: error.url,
        detail: 'The reports endpoint does not exist yet.',
      })
    }
    if (error instanceof ApiError && error.status === 501) {
      throw new ApiError(REPORTS_NOT_AVAILABLE_MESSAGE, {
        code: API_ERROR_CODES.HTTP,
        status: 501,
        url: error.url,
        detail: 'The reports endpoint is declared but not implemented.',
      })
    }
    if (error instanceof ApiError) throw error
    throw new ApiError(REPORTS_NOT_AVAILABLE_MESSAGE, { code: API_ERROR_CODES.NETWORK, url: `${API_BASE_URL}${REPORTS_ENDPOINT}` })
  }
}

/**
 * Fetch a single stored report. Not implemented on the backend yet.
 * @param {string} reportId
 */
export async function fetchReportById(reportId) {
  return fetchReports().then(({ reports }) => {
    const match = reports.find((report) => String(report.id ?? report.report_id) === String(reportId))
    if (!match) {
      throw new ApiError(`The reports endpoint returned no report with id "${reportId}".`, {
        code: API_ERROR_CODES.UNEXPECTED_SCHEMA,
        url: `${API_BASE_URL}${REPORTS_ENDPOINT}/${reportId}`,
      })
    }
    return match
  })
}

/* -------------------------------------------------------------------------- */
/* Demo data — interface preview only                                        */
/* -------------------------------------------------------------------------- */

/**
 * Sample records used exclusively to preview the dashboard interface.
 *
 * These are NOT incidents, NOT municipal records and NOT generated by the AI
 * backend. Every consumer must render the DEMO DATA label from
 * `components/reports/DemoDataNotice.jsx` alongside them.
 */
const DEMO_REPORTS = [
  {
    id: 'DEMO-1041',
    issueType: 'Pothole',
    categoryId: 'road-damage',
    severity: 'High',
    status: 'Open',
    location: 'Karve Road, Ward 12',
    reportedAt: '2026-09-18T09:20:00.000Z',
    confidence: 0.93,
    needsInspection: true,
  },
  {
    id: 'DEMO-1042',
    issueType: 'Blocked drain',
    categoryId: 'drainage-sewage',
    severity: 'Critical',
    status: 'In Review',
    location: 'Market Yard junction',
    reportedAt: '2026-09-19T14:05:00.000Z',
    confidence: 0.88,
    needsInspection: true,
  },
  {
    id: 'DEMO-1043',
    issueType: 'Water pipeline leak',
    categoryId: 'water-supply-leakage',
    severity: 'Medium',
    status: 'In Progress',
    location: 'Sector 7 service lane',
    reportedAt: '2026-09-21T07:40:00.000Z',
    confidence: 0.79,
    needsInspection: false,
  },
  {
    id: 'DEMO-1044',
    issueType: 'Damaged traffic signal',
    categoryId: 'traffic-road-safety',
    severity: 'Critical',
    status: 'Open',
    location: 'Station Road crossing',
    reportedAt: '2026-09-22T18:15:00.000Z',
    confidence: 0.86,
    needsInspection: true,
  },
  {
    id: 'DEMO-1045',
    issueType: 'Garbage accumulation',
    categoryId: 'waste-management',
    severity: 'Medium',
    status: 'Resolved',
    location: 'Riverside walk, Gate 3',
    reportedAt: '2026-09-24T11:30:00.000Z',
    confidence: 0.81,
    needsInspection: false,
  },
  {
    id: 'DEMO-1046',
    issueType: 'Damaged footpath',
    categoryId: 'footpaths-accessibility',
    severity: 'Low',
    status: 'Closed',
    location: 'College Road footpath',
    reportedAt: '2026-09-26T16:10:00.000Z',
    confidence: 0.74,
    needsInspection: false,
  },
  {
    id: 'DEMO-1047',
    issueType: 'Unclassified surface damage',
    categoryId: 'other-civic-issue',
    severity: 'Uncertain',
    status: 'In Review',
    location: 'Old highway service road',
    reportedAt: '2026-09-28T08:55:00.000Z',
    confidence: 0.52,
    needsInspection: true,
  },
  {
    id: 'DEMO-1048',
    issueType: 'Streetlight not working',
    categoryId: 'streetlights-electrical',
    severity: 'Medium',
    status: 'Open',
    location: 'Lakeview park perimeter',
    reportedAt: '2026-09-30T20:25:00.000Z',
    confidence: 0.68,
    needsInspection: false,
  },
]

/**
 * Returns a defensive copy of the labelled demo dataset.
 *
 * `category` is derived from the central category catalogue so demo rows can
 * never drift from the categories the reporting form uses, and
 * `submissionStatus` is deliberately absent: CivicFix has no submission
 * information for these fictional records, and inventing some would be the exact
 * kind of fake status this project refuses to show.
 *
 * @returns {Array<object>}
 */
export function getDemoReports() {
  return DEMO_REPORTS.map((report) => ({
    ...report,
    category: getCategoryLabel(report.categoryId),
    submissionStatus: null,
    isDemo: true,
    source: 'demo',
  }))
}
