/**
 * CivicFix AI — reports data access
 * ==========================================================================
 * Saved reports live in Supabase, but the browser never talks to Supabase:
 * everything goes through the FastAPI backend.
 *
 *   POST /reports        save a report (idempotent per `client_request_id`)
 *   GET  /reports        list saved reports (newest first)
 *
 * `getDemoReports()` (bottom of this file) returns clearly labelled sample data
 * for the dashboard preview only. The Issue Map never uses it.
 */

import { getCategoryLabel } from '@/config/issueCategories'
import { API_BASE_URL, API_ERROR_CODES, ApiError, apiRequest } from '@/services/civicfixApi'

export const REPORTS_ENDPOINT = '/reports'

/**
 * Data source currently backing the dashboard.
 * @readonly
 */
export const REPORTS_DATA_SOURCE = {
  NONE: 'none',
  API: 'api',
  DEMO: 'demo',
}

/** Reports are stored by the backend (Supabase). */
export const REPORTS_STORAGE_AVAILABLE = true

export const REPORTS_NOT_AVAILABLE_MESSAGE =
  'Saved reports could not be loaded. Check that the backend is running and that SUPABASE_URL and SUPABASE_SECRET_KEY are set in backend/.env.'

/** Map a stored row (snake_case) to the shape the dashboard and map use. */
export function normalizeStoredReport(row) {
  const latitude = Number.isFinite(Number(row?.latitude)) && row?.latitude !== null ? Number(row.latitude) : null
  const longitude = Number.isFinite(Number(row?.longitude)) && row?.longitude !== null ? Number(row.longitude) : null
  const hasCoordinates =
    latitude !== null && longitude !== null && Math.abs(latitude) <= 90 && Math.abs(longitude) <= 180

  return {
    id: row.id,
    issueType: row.issue_type ?? null,
    category: row.issue_category ?? null,
    description: row.description ?? '',
    severity: row.severity ?? null,
    confidence: typeof row.confidence === 'number' ? row.confidence : null,
    status: row.status ?? 'Open',
    location: row.location ?? '',
    reportedAt: row.created_at ?? null,
    recommendedActions: Array.isArray(row.recommended_actions) ? row.recommended_actions : [],
    suggestedDepartment: row.suggested_department ?? null,
    costMin: row.estimated_cost_min ?? null,
    costMax: row.estimated_cost_max ?? null,
    durationMinHours: row.estimated_duration_min_hours ?? null,
    durationMaxHours: row.estimated_duration_max_hours ?? null,
    latitude: hasCoordinates ? latitude : null,
    longitude: hasCoordinates ? longitude : null,
    hasCoordinates,
    needsInspection: null,
    submissionStatus: null,
    isDemo: false,
    source: 'api',
  }
}

/**
 * Retrieve saved reports from the backend.
 * @param {{ signal?: AbortSignal, timeoutMs?: number }} [options]
 * @returns {Promise<{ reports: Array<object>, source: string }>}
 */
export async function fetchReports({ signal, timeoutMs = 10000 } = {}) {
  try {
    const { data } = await apiRequest(REPORTS_ENDPOINT, { method: 'GET', signal, timeoutMs })

    const list = Array.isArray(data) ? data : Array.isArray(data?.reports) ? data.reports : null
    if (!list) {
      throw new ApiError('The reports endpoint responded with a body that is not a list of reports.', {
        code: API_ERROR_CODES.UNEXPECTED_SCHEMA,
        url: `${API_BASE_URL}${REPORTS_ENDPOINT}`,
      })
    }

    return { reports: list.map(normalizeStoredReport), source: REPORTS_DATA_SOURCE.API }
  } catch (error) {
    if (error instanceof ApiError) throw error
    throw new ApiError(REPORTS_NOT_AVAILABLE_MESSAGE, {
      code: API_ERROR_CODES.NETWORK,
      url: `${API_BASE_URL}${REPORTS_ENDPOINT}`,
    })
  }
}

/**
 * Save a report. Safe to repeat: the backend de-duplicates on
 * `client_request_id`, so a double click or retry never creates a second row.
 *
 * @param {object} payload Body built by `buildSaveReportPayload`.
 * @returns {Promise<{ report: object, created: boolean }>}
 */
export async function saveReport(payload, { signal } = {}) {
  const { data } = await apiRequest(REPORTS_ENDPOINT, {
    method: 'POST',
    body: JSON.stringify(payload),
    headers: { 'Content-Type': 'application/json' },
    signal,
    timeoutMs: 15000,
  })
  if (!data?.report) {
    throw new ApiError('The server saved nothing recognisable. Please try again.', {
      code: API_ERROR_CODES.UNEXPECTED_SCHEMA,
      url: `${API_BASE_URL}${REPORTS_ENDPOINT}`,
    })
  }
  return { report: normalizeStoredReport(data.report), created: data.created !== false }
}

/* -------------------------------------------------------------------------- */
/* Demo data — interface preview only                                        */
/* -------------------------------------------------------------------------- */

/**
 * Sample records used exclusively to preview the dashboard interface.
 *
 * These are NOT incidents, NOT municipal records and NOT generated by the AI
 * backend. Every consumer must render the DEMO DATA label from
 * `components/reports/DemoDataNotice.jsx` alongside them.
 */
const DEMO_REPORTS = [
  {
    id: 'DEMO-1041',
    issueType: 'Pothole',
    categoryId: 'road-damage',
    severity: 'High',
    status: 'Open',
    location: 'Karve Road, Ward 12',
    reportedAt: '2026-09-18T09:20:00.000Z',
    confidence: 0.93,
    needsInspection: true,
  },
  {
    id: 'DEMO-1042',
    issueType: 'Blocked drain',
    categoryId: 'drainage-sewage',
    severity: 'Critical',
    status: 'In Review',
    location: 'Market Yard junction',
    reportedAt: '2026-09-19T14:05:00.000Z',
    confidence: 0.88,
    needsInspection: true,
  },
  {
    id: 'DEMO-1043',
    issueType: 'Water pipeline leak',
    categoryId: 'water-supply-leakage',
    severity: 'Medium',
    status: 'In Progress',
    location: 'Sector 7 service lane',
    reportedAt: '2026-09-21T07:40:00.000Z',
    confidence: 0.79,
    needsInspection: false,
  },
  {
    id: 'DEMO-1044',
    issueType: 'Damaged traffic signal',
    categoryId: 'traffic-road-safety',
    severity: 'Critical',
    status: 'Open',
    location: 'Station Road crossing',
    reportedAt: '2026-09-22T18:15:00.000Z',
    confidence: 0.86,
    needsInspection: true,
  },
  {
    id: 'DEMO-1045',
    issueType: 'Garbage accumulation',
    categoryId: 'waste-management',
    severity: 'Medium',
    status: 'Resolved',
    location: 'Riverside walk, Gate 3',
    reportedAt: '2026-09-24T11:30:00.000Z',
    confidence: 0.81,
    needsInspection: false,
  },
  {
    id: 'DEMO-1046',
    issueType: 'Damaged footpath',
    categoryId: 'footpaths-accessibility',
    severity: 'Low',
    status: 'Closed',
    location: 'College Road footpath',
    reportedAt: '2026-09-26T16:10:00.000Z',
    confidence: 0.74,
    needsInspection: false,
  },
  {
    id: 'DEMO-1047',
    issueType: 'Unclassified surface damage',
    categoryId: 'other-civic-issue',
    severity: 'Uncertain',
    status: 'In Review',
    location: 'Old highway service road',
    reportedAt: '2026-09-28T08:55:00.000Z',
    confidence: 0.52,
    needsInspection: true,
  },
  {
    id: 'DEMO-1048',
    issueType: 'Streetlight not working',
    categoryId: 'streetlights-electrical',
    severity: 'Medium',
    status: 'Open',
    location: 'Lakeview park perimeter',
    reportedAt: '2026-09-30T20:25:00.000Z',
    confidence: 0.68,
    needsInspection: false,
  },
]

/**
 * Returns a defensive copy of the labelled demo dataset.
 *
 * `category` is derived from the central category catalogue so demo rows can
 * never drift from the categories the reporting form uses, and
 * `submissionStatus` is deliberately absent: CivicFix has no submission
 * information for these fictional records, and inventing some would be the exact
 * kind of fake status this project refuses to show.
 *
 * @returns {Array<object>}
 */
export function getDemoReports() {
  return DEMO_REPORTS.map((report) => ({
    ...report,
    category: getCategoryLabel(report.categoryId),
    submissionStatus: null,
    isDemo: true,
    source: 'demo',
  }))
}
